EXTERNAL_VIDEO_GENERATION_SOURCE = "external_video_generation"
EXTERNAL_VIDEO_GENERATION_MODE_TEXT_TO_VIDEO = "text_to_video"
EXTERNAL_VIDEO_GENERATION_MODE_FIRST_LAST_FRAME = "first_last_frame"
EXTERNAL_MATERIAL_GENERATION_SOURCE = "external_material_generation"
EXTERNAL_PLACEHOLDER_CAMPAIGN_SOURCES = (
    EXTERNAL_MATERIAL_GENERATION_SOURCE,
    EXTERNAL_VIDEO_GENERATION_SOURCE,
)
