EXTERNAL_VIDEO_GENERATION_SOURCE = "external_video_generation"
EXTERNAL_MATERIAL_GENERATION_SOURCE = "external_material_generation"
EXTERNAL_PLACEHOLDER_CAMPAIGN_SOURCES = (
    EXTERNAL_MATERIAL_GENERATION_SOURCE,
    EXTERNAL_VIDEO_GENERATION_SOURCE,
)
